/**
 * Boilerplate narration strings.
 *
 * The intro and outro lines are fixed by editorial convention — every video
 * opens and closes with these exact phrases. They MUST be used verbatim by
 * gen-script and SHOULD NOT be regenerated by the LLM on each run.
 *
 * Per Issue 16.
 */

export const FIXED_INTRO_NARRATION = "大家好，欢迎收看今日AI资讯。首先是资讯速览。";

export const FIXED_OUTRO_NARRATION = "以上是AI相关资讯的全部内容，我们下期再见。";

// Suggested durations are rough — gen-tts measures the real audio length and
// the renderer pads `durationInFrames` accordingly.
export const INTRO_ESTIMATED_S = 8;
export const OUTRO_ESTIMATED_S = 6;
